### ISSUE TITLE
API checklist

### ISSUE THREAD

**Issue by jpcima** [jpcima/ysfx#1]
Simple math functions
- [x] sin(angle)
- [x] cos(angle)
- [x] tan(angle)
- [x] asin(x)
- [x] acos(x)
- [x] atan(x)
- [x] atan2(x,y)
- [x] sqr(x)
- [x] sqrt(x)
- [x] pow(x,y)
- [x] exp(x)
- [x] log(x)
- [x] log10(x)
- [x] abs(x)
- [x] min(x,y)
- [x] max(x,y)
- [x] sign(x)
- [x] rand(x)
- [x] floor(x)
- [x] ceil(x)
- [x] invsqrt(x)

Time functions
- [x] time([v])
- [x] time_precise([v])

Special variables

- [x] spl0, spl1 ... spl63
- [x] spl(channelindex)
- [x] slider1, slider2, ... slider64
- [x] slider(sliderindex)
- [ ] slider_next_chg(sliderindex,nextval)
- [x] trigger
- [x] srate
- [x] num_ch
- [x] samplesblock
- [x] tempo
- [x] play_state
- [x] play_position
- [x] beat_position
- [x] ts_num
- [x] ts_denom
- [x] ext_noinit
- [ ] ext_nodenorm
- [x] reg00-reg99
- [x] _global.*
- [ ] pdc_delay
- [ ] pdc_bot_ch, pdc_top_ch
- [ ] pdc_midi

MIDI functions
- [x] midisend(offset,msg1,msg2)
- [x] midisend(offset,msg1,msg2 + (msg3 * 256))
- [x] midisend(offset,msg1,msg2,msg3)
- [x] midisend_buf(offset,buf, len)
- [x] midisend_str(offset,string)
- [x] midirecv(offset,msg1,msg23)
- [x] midirecv(offset,msg1,msg2,msg3)
- [x] midirecv_buf(offset,buf, maxlen)
- [x] midirecv_str(offset, string)
- [x] midisyx(offset,msgptr,len)
- [x] ext_midi_bus
- [x] midi_bus

File I/O and Serialization
- [x] file_open(index or slider)
- [x] file_close(handle)
- [x] file_rewind(handle)
- [x] file_var(handle,variable)
- [x] file_mem(handle,offset, length)
- [x] file_avail(handle)
- [x] file_riff(handle,nch,samplrate)
- [x] file_text(handle,istext)
- [x] file_string(handle,str)

Memory/Slider/FFT/MDCT Functions
- [x] mdct(start_index, size), imdct(start_index, size)
- [x] fft(start_index, size), ifft(start_index, size)
- [x] fft_real(start_index, size), ifft_real(start_index, size)
- [x] fft_permute(index,size), fft_ipermute(index,size)
- [x] convolve_c(dest,src,size)

Memory Utility
- [x] freembuf(top)
- [x] memcpy(dest,source,length)
- [x] memset(dest,value,length)
- [x] __memtop()

Stack
- [x] stack_push(value)
- [x] stack_pop(value)
- [x] stack_peek(index)
- [x] stack_exch(value)

Slider Functions
- [x] sliderchange(mask or sliderX)
- [x] slider_automate(mask or sliderX)
- [x] slider_show(mask or sliderX[, value])

Atomic Variable Access
- [x] atomic_setifequal(dest,value,newvalue)
- [x] atomic_exch(val1,val2)
- [x] atomic_add(dest_val1,val2)
- [x] atomic_set(dest_val1,val2)
- [x] atomic_get(val)

Pin Mapper Functions
- [ ] get_host_numchan()
- [ ] set_host_numchan(numchan)
- [ ] get_pin_mapping(inout,pin,startchan,chanmask)
- [ ] set_pin_mapping(inout,pin,startchan,chanmask,mapping)
- [ ] get_pinmapper_flags(no parameters)
- [ ] set_pinmapper_flags(flags)

String functions
- [x] strlen(str)
- [x] strcpy(str, srcstr)
- [x] strcat(str, srcstr)
- [x] strcmp(str, str2)
- [x] stricmp(str, str2)
- [x] strncmp(str, str2, maxlen)
- [x] strnicmp(str, str2, maxlen)
- [x] strncpy(str, srcstr, maxlen)
- [x] strncat(str, srcstr, maxlen)
- [x] strcpy_from(str,srcstr, offset)
- [x] strcpy_substr(str,srcstr, offset, maxlen)
- [x] str_getchar(str, offset[, type])
- [x] str_setchar(str, offset, value[, type])
- [ ] strcpy_fromslider(str, slider)
- [x] sprintf(str,format, ...)
- [x] match(needle, haystack, ...)
- [x] matchi(needle, haystack, ...)

Graphics
- [x] gfx_set(r[g,b,a,mode,dest])
- [x] gfx_lineto(x,y,aa)
- [x] gfx_line(x,y,x2,y2[,aa])
- [x] gfx_rectto(x,y)
- [x] gfx_rect(x,y,w,h)
- [x] gfx_setpixel(r,g,b)
- [x] gfx_getpixel(r,g,b)
- [x] gfx_drawnumber(n,ndigits)
- [x] gfx_drawchar($'c')
- [x] gfx_drawstr(str[,flags,right,bottom])
- [x] gfx_measurestr(str,w,h)
- [x] gfx_setfont(idx[,fontface, sz, flags])
- [x] gfx_getfont()
- [x] gfx_printf(str, ...)
- [x] gfx_blurto(x,y)
- [x] gfx_blit(source, scale, rotation)
- [x] gfx_blit(source, scale, rotation[, srcx, srcy, srcw, srch, destx, desty, destw, desth, rotxoffs, rotyoffs])
- [x] gfx_blitext(source, coordinatelist, rotation)
- [x] gfx_getimgdim(image, w, h)
- [x] gfx_setimgdim(image, w,h)
- [x] gfx_loadimg(image, filename)
- [x] gfx_gradrect(x,y,w,h, r,g,b,a[, drdx, dgdx, dbdx, dadx, drdy, dgdy, dbdy, dady])
- [x] gfx_muladdrect(x,y,w,h, mul_r, mul_g, mul_b[, mul_a, add_r, add_g, add_b, add_a])
- [x] gfx_deltablit(srcimg,srcx,srcy,srcw,srch, destx, desty, destw, desth, dsdx, dtdx, dsdy, dtdy, dsdxdy, dtdxdy[, usecliprect=1] )
- [x] gfx_transformblit(srcimg, destx, desty, destw, desth, div_w, div_h, table)
- [x] gfx_circle(x,y,r[,fill,antialias])
- [x] gfx_roundrect(x,y,w,h,radius[,antialias])
- [x] gfx_arc(x,y,r, ang1, ang2[,antialias])
- [x] gfx_triangle(x1,y1,x2,y2,x3,y3[,x4,y4,...])
- [x] gfx_getchar([char])
- [x] gfx_showmenu("str")
- [x] gfx_setcursor(resource_id[,"custom cursor name"])
- [x] gfx_getdropfile(idx[,#str]) (not documented in JSFX)
- [x] gfx_r, gfx_g, gfx_b, gfx_a
- [x] gfx_w, gfx_h
- [x] gfx_x, gfx_y
- [x] gfx_mode
- [x] gfx_clear
- [x] gfx_dest
- [x] gfx_texth
- [ ] gfx_ext_retina (lib OK, plugin needs work)
- [x] mouse_x
- [x] mouse_y
- [x] mouse_cap
- [x] mouse_wheel
- [x] mouse_hwheel
